# to I need AARCH32_SP ?

build:
    . /opt/amy/1.0/environment-setup-cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi && \
        unset LDFLAGS && unset CFLAGS && unset CPPFLAGS && \
        bear -- make CROSS_COMPILE=arm-none-eabi- \
        STM32MP_SDMMC=1 \
        PLAT=stm32mp1 \
        ARCH=aarch32 ARM_ARCH_MAJOR=7 \
        DTB_FILE_NAME=stm32mp157f-dk2.dtb \
        STM32MP1_OPTEE_IN_SYSRAM=1 \
        LOG_LEVEL=40 \
        DEBUG=1 \
        all \
        -j16

flash: build
    if [ -b "/dev/disk/by-partlabel/fsbl1" ]; then \
        sudo dd if=build/stm32mp1/debug/tf-a-stm32mp157f-dk2.stm32 of=/dev/disk/by-partlabel/fsbl1 bs=256K ; \
        sudo dd if=build/stm32mp1/debug/tf-a-stm32mp157f-dk2.stm32 of=/dev/disk/by-partlabel/fsbl2 bs=256K ; \
    else \
        echo "Error: /dev/disk/by-partlabel/fsbl1 not found. Is the SD card mounted?" ; \
    fi

openocd:
     openocd -f board/stm32mp15x_dk2.cfg

gdb:
    arm-none-eabi-gdb \
        -ex "set confirm off" \
        -ex "target extended-remote :3333" \
        -ex "add-symbol-file ../optee_os/out/arm-plat-stm32mp1/core/tee.elf" \
        -ex "add-symbol-file ../u-boot/u-boot" \
        -ex "add-symbol-file ../linux/vmlinux" \
        build/stm32mp1/debug/bl2/bl2.elf

clean:
    make realclean

decompile:
    dtc -I dtb -O dts -o stm32mp157f-dk2.dts build/stm32mp1/debug/fdts/stm32mp157f-dk2-bl2.dtb

# AARCH32_SP_OPTEE ?
# IMAGE_BL32 ?
# PSA_FWU_SUPPORT=0