#@TYPE: Machine
#@NAME: stm32mp1-dk2 machine
#@DESCRIPTION: Machine configuration for the STM32MP1-DK2 board

DEFAULTTUNE = "cortexa7thf-neon-vfpv4"
require conf/machine/include/arm/armv7a/tune-cortexa7.inc

# MACHINE_FEATURES += "bluetooth"
# MACHINE_FEATURES += "wifi"

KERNEL_IMAGETYPE = "zImage"

IMAGE_FSTYPES = "ext4"

PREFERRED_PROVIDER_virtual/tf-a = "tf-a-st-amy"
PREFERRED_PROVIDER_virtual/kernel = "linux-amy"
PREFERRED_PROVIDER_virtual/u-boot = "u-boot"
PREFERRED_PROVIDER_virtual/optee = "optee-os"

PREFERRED_VERSION_tf-a-st-amy = "2.10.13"

# op-tee >= 4.8.0 is currently broken (see stm32_rtc_init issue in core/drivers/stm32_rtc.c)
# see log file mp1-optee-4.8.0-rtc-error.txt
PREFERRED_VERSION_optee-os = "4.7.0"
PREFERRED_VERSION_u-boot = "2026.04"
PREFERRED_VERSION_linux-amy = "6.19%"

SERIAL_CONSOLES = "115200;ttySTM0"

# TODO use consistent naming
TFA_DEVICETREE = "stm32mp157f-dk2"
KERNEL_DEVICETREE = "st/stm32mp157f-dk2-amy.dtb"

# optee
# stm32mp157f-dk2 is missing from optee mainline, it is only available in patch from meta-st-stm32mp layer:
# recipes-security/optee/optee-os-stm32mp/0001-4.0.0-stm32mp-r3.patch
OPTEE_PLATFORM   = "stm32mp1-157C_DK2"
OPTEE_DEVICETREE = "stm32mp157c-dk2"

# u-boot
UBOOT_CONFIG = "stm32mp157f-dk2-amy_defconfig"
UBOOT_DEVICETREE = "st/stm32mp157f-dk2"

SDIMAGE_CONF = "sdcard_genimage_mp1.cfg.in"