#@TYPE: Machine
#@NAME: stm32mp1-dk2 machine
#@DESCRIPTION: Machine configuration for the STM32MP1-DK2 board

DEFAULTTUNE = "cortexa7thf-neon-vfpv4"
require conf/machine/include/arm/armv7a/tune-cortexa7.inc

# MACHINE_FEATURES += "bluetooth"
# MACHINE_FEATURES += "wifi"

KERNEL_IMAGETYPE = "zImage"

IMAGE_FSTYPES = "ext4"

PREFERRED_PROVIDER_virtual/tf-a = "tf-a-st-amy"
PREFERRED_PROVIDER_virtual/kernel = "linux-amy"
PREFERRED_PROVIDER_virtual/u-boot = "u-boot"

PREFERRED_VERSION_u-boot = "2026.01"

# op-tee >= 4.8.0 is currently broken (see stm32_rtc_init issue in core/drivers/stm32_rtc.c)
PREFERRED_VERSION_optee-os = "4.7.0"
PREFERRED_VERSION_linux-amy = "6.19%"

SERIAL_CONSOLES = "115200;ttySTM0"

# TODO use consistent naming
TFA_DEVICETREE = "stm32mp157f-dk2"
KERNEL_DEVICETREE = "st/stm32mp157f-dk2-amy.dtb"

# u-boot
UBOOT_CONFIG = "amy_defconfig"
UBOOT_DEVICETREE = "st/stm32mp157f-dk2"

SDIMAGE_CONF = "sdcard_genimage_mp1.cfg.in"