#@TYPE: Machine
#@NAME: stm32mp257-dk machine
#@DESCRIPTION: Machine configuration for the STM32MP257-DK board

DEFAULTTUNE = "cortexa35"
include conf/machine/include/arm/armv8a/tune-cortexa35.inc

# MACHINE_FEATURES += "bluetooth"
# MACHINE_FEATURES += "wifi"

KERNEL_IMAGETYPE = "Image"

IMAGE_FSTYPES = "ext4"

PREFERRED_PROVIDER_virtual/tf-a = "tf-a-st"
PREFERRED_PROVIDER_virtual/kernel = "linux-amy"
PREFERRED_PROVIDER_virtual/u-boot = "u-boot"
PREFERRED_PROVIDER_virtual/optee-os = "optee-os-st"

PREFERRED_VERSION_tf-a-st = "2.10.24"
PREFERRED_VERSION_u-boot = "2026.04"
PREFERRED_VERSION_linux-amy = "7.0.%"

SERIAL_CONSOLES = "115200;ttySTM0"

# TODO use consistent naming
TFA_DEVICETREE = "stm32mp257f-dk"
KERNEL_DEVICETREE = "st/stm32mp257f-dk.dtb"

# u-boot
UBOOT_CONFIG = "stm32mp25_defconfig"
UBOOT_DEVICETREE = "st/stm32mp257f-dk"

SDIMAGE_CONF = "sdcard_genimage_mp2.cfg.in"

OPTEE_DEBUG = "0"