# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-bsp-st"
BBFILE_PATTERN_meta-bsp-st = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-bsp-st = "6"

LAYERDEPENDS_meta-bsp-st = "core"
LAYERSERIES_COMPAT_meta-bsp-st = "scarthgap"

PREFERRED_PROVIDER_virtual/tf-a ??= "tf-a-st-amy"
PREFERRED_PROVIDER_virtual/kernel ??= "linux-amy"

PREFERRED_VERSION_tf-a ??= "2.14.2"
PREFERRED_VERSION_tf-a-st ??= "2.10.13"

# op-tee >= 4.8.0 is currently broken (see stm32_rtc_init issue in core/drivers/stm32_rtc.c)
PREFERRED_VERSION_optee-os ?= "4.7.0"
PREFERRED_VERSION_linux-amy ?= "6.19%"

# Define location of binaries in sysroot
FIP_DIR_OPTEE_BASE ?= "/optee-os"
FIP_DIR_TFA_BASE ?= "/tf-a"
FIP_DIR_DDR_PHY_BASE ?= "/stm32mp-ddr-phy"

AMY_DEBUG ??= "1"