require conf/distro/poky.conf

DISTRO = "amy"
DISTRO_VERSION = "1.0"
DISTRO_NAME = "Amy distribution"

PACKAGE_CLASSES = "package_rpm"

# DISTRO_FEATURES += "sysvinit"
# INIT_MANAGER = "sysvinit"

INIT_MANAGER = "systemd"
# DISTRO_FEATURES += "systemd"

DISTRO_EXTRA_RDEPENDS += ""
DISTRO_EXTRA_RRECOMMENDS += ""