require conf/distro/poky.conf

DISTRO = "amy"
DISTRO_VERSION = "1.0"
DISTRO_NAME = "Amy distribution"

PACKAGE_CLASSES = "package_rpm"

INIT_MANAGER = "sysvinit"
DISTRO_FEATURES += "sysvinit"

DISTRO_FEATURES += "virtualization"
DISTRO_FEATURES += "seccomp"

DISTRO_EXTRA_RDEPENDS += ""
DISTRO_EXTRA_RRECOMMENDS += ""