#!/bin/sh
### BEGIN INIT INFO
# Provides:          usb-gadget-ncm
# Required-Start:    $local_fs udev
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: USB CDC-NCM gadget
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

case "$1" in
    start)
        /usr/sbin/usb-gadget-ncm start || exit $?
        ;;

    stop)
        /usr/sbin/usb-gadget-ncm stop || true
        ;;

    restart)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 2
        ;;
esac

exit 0